spotify/gordon-gcp

- docs/clients.rst
- docs/conf.py
- docs/exceptions.rst
- docs/index.rst
- gordon_gcp/__init__.py
- gordon_gcp/clients/__init__.py
- gordon_gcp/clients/_utils.py
- gordon_gcp/clients/auth.py
- gordon_gcp/clients/http.py
- gordon_gcp/exceptions.py
- requirements.txt
- test-requirements.txt
- tests/unit/clients/__init__.py
- tests/unit/clients/test_auth.py
- tests/unit/clients/test_http.py
- tests/unit/conftest.py
- tox.ini
We'll be needing the same functionality that the asynchronous [auth](https://github.com/spotify/gordon-janitor-gcp/blob/49c4fc875ab4cbc12b7fde6ecc4163c8fed63e95/gordon_janitor_gcp/clients/auth.py) and [http](https://github.com/spotify/gordon-janitor-gcp/blob/49c4fc875ab4cbc12b7fde6ecc4163c8fed63e95/gordon_janitor_gcp/clients/http.py) clients bring in this plugin library. Rather than extracting this out into a third "common/shared" library, the gordon-janitor-gcp package will just depend on this. There might be future need to move the Google product API clients into here as well, but I wasn't certain. I also skipped the paginator mixin because I don't _think_ it will be needed. But it'll be easy to add that in if I'm wrong.
Once this is merged in, …
> Move async auth and http clients from janitor-gcp

- CONTRIBUTING.rst
This PR helps clarify the workflow around release branches.
N/A
N/A
```release-note
NONE
```
@econchick @spotify/alf
> Clarify branching workflow

- src/gordon_gcp/plugins/enricher.py
- tests/unit/conftest.py
- tests/unit/plugins/test_enricher.py
- tests/unit/plugins/test_event_consumer.py
- tox.ini
This PR implements the IEnricherClient interface. It does not implement the Builder or the Spotify-specific parts of the code - those will be left for future PRs. 
N/A
This PR is rebased off #9 because it depends on certain parts of that PR to function, which is why this PR is in "RFC" state. If you'd like to give me feedback before #9 is merged, check out commit 5525260.
```release-note
NONE
```
@spotify/alf
> Implement IEnricher interface

- src/gordon_gcp/plugins/enricher.py
- tests/unit/plugins/test_init.py
Fix a typo, add a couple of clarifying comments, and fix formatting of a function call.
Fixes #
```release-note
```
> Typos, formatting, comments in enricher

- src/gordon_gcp/plugins/enricher.py
- tests/unit/plugins/test_init.py
Factor out validations for easier subclassing.
Fixes #
```release-note
```
> Enricher builder hook

- gordon.toml.example
- src/gordon_gcp/exceptions.py
- src/gordon_gcp/plugins/publisher.py
- tests/unit/plugins/test_publisher.py
Adds the Publisher plugin for Google Cloud DNS
Fixes # N/A
```release-note
NONE
```
@spotify/alf
> Add Publisher plugin for Google Cloud DNS

- gordon.toml.example
The code uses dns_zone in multiple places, and also has managed_zone.  They should be in the sample config in the correct places.
Fixes #
```release-note
```
> fix config to properly show dns zone vars

- OWNERS
- README.rst
- docs/schema.rst
- src/gordon_gcp/plugins/janitor/__init__.py
- src/gordon_gcp/plugins/janitor/reconciler.py
- src/gordon_gcp/plugins/service/__init__.py
- tests/unit/plugins/service/test_gdns_publisher.py
- tests/unit/plugins/service/test_init.py
Updates and fixes OWNERS
Adds janitor plugin summaries - was a TODO
Cleans up some capitalizations and wordings
Suppresses a test warning - seems to have moved, also made the suppression more specific
Fixes #
```release-note
Updated and fixed OWNERS
Added janitor plugin summaries
Cleaned up some capitalizations and wordings
Suppressed a test warning
```
> Clean up some phrasing, TODOs, etc.

- CHANGELOG.rst
- src/gordon_gcp/__init__.py
Bumps version to v0.0.1.dev4.
Fixes #
```release-note
```
> Prepare v0.0.1.dev4 release

- src/gordon_gcp/plugins/service/gdns_publisher.py
- tests/unit/plugins/service/test_init.py
We need to separate the marshaling of resource records and the processing of each record so we can change the marshaling in subclasses.
Fixes #
```release-note
Refactored GDNSPublisher for easy subclassing/overriding.
```
> Refactor record marshaling and processing in GDNS publisher

- CHANGELOG.rst
- src/gordon_gcp/__init__.py
Bumps version to v0.0.1.dev5.
Fixes #
```release-note
```
> Prepare v0.0.1.dev5 release

- src/gordon_gcp/plugins/service/gdns_publisher.py
- tests/unit/plugins/service/test_gdns_publisher.py
Changes where/if certain variables are set to make it easier to subclass and override.
Fixes #
```release-note
Internal API improvements.
```
> Change some variable handling in the GDNS publisher

- src/gordon_gcp/plugins/service/enricher.py
- src/gordon_gcp/plugins/service/event_consumer.py
- src/gordon_gcp/plugins/service/gdns_publisher.py
- tests/unit/plugins/service/test_enricher.py
- tests/unit/plugins/service/test_event_consumer.py
- tests/unit/plugins/service/test_gdns_publisher.py
- tests/unit/plugins/service/test_init.py
To be consistent with the new routing logic which handles phase updates and error handling, plugins should avoid routing directly.
Fixes #
@spotify/alf 
```release-note
Fix: remove routing logic from plugins
```
> Remove routing logic from plugins

- requirements.txt
- src/gordon_gcp/plugins/janitor/gpubsub_publisher.py
- src/gordon_gcp/plugins/service/__init__.py
- src/gordon_gcp/plugins/service/enricher.py
- src/gordon_gcp/plugins/service/event_consumer.py
- src/gordon_gcp/plugins/service/gdns_publisher.py
- tests/unit/conftest.py
- tests/unit/plugins/janitor/test_gpubsub_publisher.py
- tests/unit/plugins/janitor/test_init.py
- tests/unit/plugins/service/test_enricher.py
- tests/unit/plugins/service/test_event_consumer.py
- tests/unit/plugins/service/test_gdns_publisher.py
- tests/unit/plugins/service/test_init.py
* Update gordon-dns to 0.0.1.dev3
-- Replace interfaces
-- Reorder init args to include required args first
* Move asserts outside of error context to actually assert
Fixes #
@spotify/alf 
```release-note
* Update gordon-dns to 0.0.1.dev3
```
> Update gordon-dns to 0.0.1.dev3

- src/gordon_gcp/plugins/service/enricher.py
- tests/unit/plugins/service/test_enricher.py
This reorders the args to the GCEEnricher `__init__` method so the interface required args are before any additional args.
Fixes #
@spotify/alf  This change is to be consistent with the publisher and the interface.
```release-note
* Reorder GCEEnricher init args.
```
> Reorder GCEEnricher init args

- CHANGELOG.rst
- src/gordon_gcp/__init__.py
Prepare for v0.0.1.dev8 release with reordered enricher args for consistency.
Fixes #
@spotify/alf 
```release-note
```
> Prepare v0.0.1.dev8 release

- requirements.txt
New releases 🎉 🎁 h/t to @smstone for catching [this](https://github.com/spotify/gordon-gcp/pull/37#discussion_r196859540).
Fixes #
```release-note
```
> Bump gordon-dns dependency to latest

- CHANGELOG.rst
- src/gordon_gcp/__init__.py
Prepare dev release 0.0.1.dev9 🎉 
Fixes #
```release-note
```
> Prepare dev release 0.0.1.dev9

- src/gordon_gcp/plugins/service/enricher.py
This PR changes the Google Compute API url used in the enriching phase. The original URL is incorrect and returning 404s on requests.
Fixes #
```release-note
Update the Google API compute v1 endpoint URL.
```
@spotify/alf
> Update the Google API compute v1 endpoint URL

- CHANGELOG.rst
- src/gordon_gcp/__init__.py
Prepare dev release 0.0.1.dev10
Fixes #
```release-note
```
> Prepare dev release 0.0.1.dev10

- src/gordon_gcp/plugins/janitor/authority.py
- tests/unit/plugins/janitor/test_authority.py
This PR skips projects where a HTTP error is raised when attempting to list the project's instances. 
This is needed due because when a GCP project is deleted, the instances endpoint will return a 404. 
Fixes #
```release-note
Janitor: Skip project if listing instances fails.
```
@spotify/alf
> Janitor: Skip project if listing instances fails.

- CHANGELOG.rst
- src/gordon_gcp/__init__.py
Prepare dev release 0.0.1.dev11
Fixes #
```release-note
```
> Prepare v0.0.1.dev11 release

- CHANGELOG.rst
- src/gordon_gcp/__init__.py
Yay release day! 🎁 
Fixes #
```release-note
```
> Prepare dev release 0.0.1.dev13

- src/gordon_gcp/clients/gdns.py
Fixes #
```release-note
```
@ocsw 
//cc @spotify/alf
> Set default for GCPResourceRecordSet kind attribute

- src/gordon_gcp/plugins/janitor/authority.py
Currently the code serially processes requests to get a list of instances per project. While it doesn't block other tasks on the loop, it still goes through one project at a time. This patch queues up API requests and initiates them all at once, about 100 connections per host (googleapis.com) at a time. 
Here's some example output:
```log
2018-07-10T18:08:23.935Z gordon-janitor (11) DEBUG: Using selector: EpollSelector
2018-07-10T18:08:24.524Z gordon-janitor (11) DEBUG: Making request: POST https://accounts.google.com/o/oauth2/token
2018-07-10T18:08:24.527Z gordon-janitor (11) DEBUG: Starting new HTTPS connection (1): accounts.google.com:443
2018-07-10T18:08:24.741Z gordon-janitor (11) DEBUG: https://accounts.google.com:443 "POST /o/oauth2/token …
```
> Add request concurrency to GCE listing of instances

- CHANGELOG.rst
- src/gordon_gcp/__init__.py
Release day! \o/ 🎁 
Fixes #
```release-note
```
> Prepare dev release 0.0.1.dev14

- src/gordon_gcp/plugins/janitor/reconciler.py
- tests/unit/plugins/janitor/test_reconciler.py
I realized that if we pull every record from GDNS in the authority, it will include SOA and NS. If those are present in the GHE input, they will be ignored, and it'll try to add them every time. If not, and we have deletion, we may try to delete them (which will either fail or blow up). So we need to remove SOA and NS records from the comparison in the authority. Note that this only applies to NS records for the root of the zone; Google seems to accept others in my testing.
Fixes #
```release-note
Filtered out SOA/NS from janitor reconciliation.
```
> Filter out root SOA/NS records in reconciler

- src/gordon_gcp/clients/_utils.py
- src/gordon_gcp/clients/auth.py
- src/gordon_gcp/clients/http.py
- tests/unit/clients/test_auth.py
- tests/unit/clients/test_http.py
This adds more detail to HTTP request and response logging so it is easier to understand what was actually requested.
Fixes #
@spotify/alf 
```release-note
Increase level of detail in HTTP request/response logging.
```
> Increase http logging

- CHANGELOG.rst
- src/gordon_gcp/__init__.py
create release
Fixes #
@spotify/alf 
```release-note
```
> Prepare v0.0.dev15 release

- src/gordon_gcp/plugins/janitor/authority.py
Fix incorrect and superfluous authority logging.
Fixes #
@spotify/alf 
```release-note
Fix incorrect and superfluous authority logging.
```
>  Fix incorrect and superfluous authority logging

- docs/exceptions.rst
- src/gordon_gcp/clients/auth.py
- src/gordon_gcp/clients/http.py
- src/gordon_gcp/exceptions.py
- src/gordon_gcp/plugins/janitor/authority.py
- src/gordon_gcp/plugins/service/gdns_publisher.py
- tests/unit/clients/test_auth.py
- tests/unit/clients/test_http.py
- tests/unit/plugins/janitor/test_authority.py
- tests/unit/plugins/service/test_enricher.py
- tests/unit/plugins/service/test_gdns_publisher.py
This causes an authority to fail if it has an incomplete view of a zone, and changes error handling a bit in order to avoid reimplementing every 4xx/5xx HTTP response code as a specific exception.
Fixes #
@spotify/alf 
```release-note
* Fail authority if it cannot get a full view of of all instances.
* Simplify HTTP error response handling.
```
> Handle http response errors

- src/gordon_gcp/plugins/janitor/authority.py
- src/gordon_gcp/plugins/janitor/reconciler.py
- tests/unit/plugins/janitor/test_reconciler.py
This adds deletions to the janitor's reconciler.
Fixes #
```release-note
Added deletions to the janitor reconciler
```
> Add deletion to the janitor reconciler

- CHANGELOG.rst
- src/gordon_gcp/__init__.py
Fixes #
@spotify/alf 
```release-note
Prepare 0.0.1.dev16 release.
```
> Prepare 0.0.1.dev16 release

- src/gordon_gcp/plugins/janitor/gpubsub_publisher.py
- tests/unit/conftest.py
- tests/unit/plugins/janitor/test_gpubsub_publisher.py
Improves gpubsub_publisher logging, removing completed futures or (in the future) adding metrics.
Fixes #
@spotify/alf 
```release-note
Add callback in pubsub publisher.
```
> Add pubsub publisher callback

- src/gordon_gcp/clients/gce.py
This changes the default maxResults to 100 when listing instances. We've found we occasionally receive HTTP 500s from Google APIs with projects with a lot of instance churn when using the max results of 500.
Fixes #
```release-note
```
@spotify/alf
> Default max results to 100 when listing instances

- src/gordon_gcp/plugins/janitor/authority.py
We may see a HTTP 403 returned when fetching projects that are either new or testing.
Fixes #
```release-note
```
@spotify/alf
> Add 403 to project skip response codes

- CHANGELOG.rst
- src/gordon_gcp/__init__.py
Prepares 0.0.1.dev18 release
Fixes #
```release-note
```
@spotify/alf
> Prepare 0.0.1.dev18 release

- src/gordon_gcp/clients/gdns.py
We were previously stripping the returned fields down to a specific set, which did not contain the nextPageToken field for paging.
Fix rrset paging in dns client. We were previously stripping the returned fields down to a specific set, which did not contain the nextPageToken field for paging.
Fixes #
@spotify/alf 
```release-note
Fix rrset paging in dns client.
```
> Fix rrset paging in dns client

- src/gordon_gcp/clients/gdns.py
Accidentally merged this directly to master
Reverts spotify/gordon-gcp#69
> Revert "Fix rrset paging in dns client"

- src/gordon_gcp/clients/gdns.py
@spotify/alf recreating this PR, since I accidentally merged the [last one](https://github.com/spotify/gordon-gcp/pull/69) to master...
Fixes #
```release-note
Fix rrset paging in reconciler.
```
> Fix rrset paging

- docs-requirements.txt
- docs/config-service.rst
- gordon.toml.example
- requirements.txt
- setup.py
- src/gordon_gcp/plugins/service/event_consumer.py
- tests/unit/conftest.py
- tests/unit/plugins/service/test_event_consumer.py
- tests/unit/plugins/service/test_init.py
Drop messages older than a configured limit so we don't get overloaded when Gordon hasn't been running for a while.  (And high latency, and high DNS churn...)
Fixes #
```release-note
Added past_window old-message dropping.
```
> Drop messages older than a limit

- CHANGELOG.rst
- src/gordon_gcp/__init__.py
Bump to version 0.0.1.dev19.
Fixes #
```release-note
```
> Prepare 0.0.1.dev19 release

- src/gordon_gcp/clients/gdns.py
Fix a typo in a log message for GDNS.
Fixes #
```release-note
NONE
```
> Add missing word in log message

- requirements.txt
- src/gordon_gcp/plugins/janitor/__init__.py
- src/gordon_gcp/plugins/janitor/authority.py
- src/gordon_gcp/plugins/janitor/gpubsub_publisher.py
- src/gordon_gcp/plugins/janitor/reconciler.py
- tests/unit/conftest.py
- tests/unit/plugins/janitor/test_authority.py
- tests/unit/plugins/janitor/test_gpubsub_publisher.py
- tests/unit/plugins/janitor/test_init.py
- tests/unit/plugins/janitor/test_reconciler.py
- tests/unit/plugins/service/test_event_consumer.py
Adds metrics around janitor GCP plugins
Fixes #
```release-note
Add metrics to janitor GCP plugins
```
@spotify/alf
> Add metrics to janitor plugins

- src/gordon_gcp/plugins/janitor/reconciler.py
From watching janitor logs in realtime, I have figured out that we are spending a LOT of time in the list comprehensions in the reconciler that do the comparisons between desired and actual.  If we change these lookups to use dicts, I suspect we can shave a lot of time off.  (The existing comprehensions are O(n^2), the new version is O(n) because dicts are hashed.)
Fixes #
```release-note
Sped up the reconciler.
```
> Speed up reconciler

- CHANGELOG.rst
- src/gordon_gcp/__init__.py
Bump to version 0.0.1.dev20.
Fixes #
```release-note
```
> Prepare 0.0.1.dev20 release

- CHANGELOG.rst
- src/gordon_gcp/__init__.py
Prepare 0.0.1.dev21 release.
Fixes #
```release-note
```
> Prepare 0.0.1.dev21 release

- CHANGELOG.rst
- src/gordon_gcp/__init__.py
Prepare 0.0.1.dev22 release.
Fixes #
```release-note
```
> Prepare 0.0.1.dev22 release

- src/gordon_gcp/clients/http.py
- tests/unit/clients/test_http.py
We are seeing aiohttp request calls dying with timeouts.  This logs more info so we can figure out which ones are timing out.
Partial traceback:
```
File "/usr/src/app/.venv/lib/python3.6/site-packages/gordon_gcp/plugins/janitor/authority.py", line 155, in _filter_results
raise result
File "/usr/src/app/.venv/lib/python3.6/site-packages/gordon_gcp/clients/gce.py", line 116, in list_instances
responses = await self.list_all(url, params)
File "/usr/src/app/.venv/lib/python3.6/site-packages/gordon_gcp/clients/_utils.py", line 51, in list_all
response = await self.get_json(url, params=params)
File "/usr/src/app/.venv/lib/python3.6/site-packages/gordon_gcp/clients/http.py", line 196, in get_json
response = await self.request(method='get', url=url, …
```
> Log aiohttp request call failures

- src/gordon_gcp/schema/validate.py
Reduces output of validation errors. Because of how we do validation against an array of schemas, these validation errors occur on receipt of every event message. 
This PR changes the output from: 
```
2018-09-20T16:40:57.725Z gordon[1]: Given message was not valid against the schema "audit-log"
Traceback (most recent call last):
File "/usr/src/app/.venv/lib/python3.6/site-packages/gordon_gcp/schema/validate.py", line 127, in validate
jsonschema.validate(message, self.schemas[schema_name])
File "/usr/src/app/.venv/lib/python3.6/site-packages/jsonschema/validators.py", line 541, in validate
cls(schema, *args, **kwargs).validate(instance)
File "/usr/src/app/.venv/lib/python3.6/site-packages/jsonschema/validators.py", line 130, in validate
raise error …
```
> Limit output of validation errors

- CHANGELOG.rst
- src/gordon_gcp/__init__.py
Prepare release 0.0.1.dev25 with less jsonschema validation logging.
Fixes #
@spotify/alf 
```release-note
```
> Prepare 0.0.1.dev25 release

- docs/conf.py
External dependency changed.
Fixes #
```release-note
```
> Fix Google URL that changed on us

- CHANGELOG.rst
- src/gordon_gcp/__init__.py
Prepare release 0.0.1.dev26.
Fixes #
```release-note
```
> Prepare 0.0.1.dev26 release

- CHANGELOG.rst
- src/gordon_gcp/__init__.py
Prepare 0.0.1.dev27 release.
Fixes #
```release-note
```
> Prepare 0.0.1.dev27 release

- CHANGELOG.rst
- src/gordon_gcp/__init__.py
> Prepare release 0.0.1.dev28

- docs/config-janitor.rst
- src/gordon_gcp/plugins/janitor/authority.py
- tests/unit/plugins/janitor/test_authority.py
Add a project whitelist to specify a project to run janitor against, makes testing easier.
Fixes #
If the project_whitelist is set, the authority will only look at those projects for fetching instances. Blacklist and active projects are ignored.
```release-note
Add a project whitelist to Janitor Authority
```
> Add project whitelist for janitor authority

- CHANGELOG.rst
- src/gordon_gcp/__init__.py
Prepare release 0.0.1.dev29
Fixes #
```release-note
```
> Prepare release 0.0.1.dev29

- src/gordon_gcp/plugins/service/gdns_publisher.py
We currently don't get much insight on records published (or failed to publish). This adds a few simple metrics to the GDNSPublisher.
Fixes #
n/a
```release-note
Add metrics for record dispatching.
```
@spotify/alf
> Add metrics for record dispatch/publishing

- CHANGELOG.rst
- src/gordon_gcp/__init__.py
Prepare release 0.0.1.dev31
Fixes #
@spotify/alf 
```release-note
N/A
```
> Prepare release 0.0.1.dev31

- docs-requirements.txt
- requirements.txt
Bumping google-cloud-pubsub library to avoid depending on a non-release version.
> Set google-cloud-pubsub to latest released version

- src/gordon_gcp/plugins/service/event_consumer.py
- tests/unit/plugins/service/test_event_consumer.py
If Gordon cannot create a pubsub subscription, there is no point in continuing running.
Add logic for retrying, and exiting if it fails repeatedly to create a subscription.
> [event_consumer] kill Gordon on repeated subscribe failure

- CHANGELOG.rst
- src/gordon_gcp/__init__.py
> Prepare v0.0.1.dev32 release

- docs/conf.py
- test-requirements.txt
- tox.ini
Fix the build error in https://github.com/spotify/gordon-gcp/pull/113
Fixes #
Build issues in https://github.com/spotify/gordon-gcp/pull/113
Also reorders py.test and flake8 because I think it's handy for local debugging.
```release-note
```
> Fix build issues

- CHANGELOG.rst
- src/gordon_gcp/__init__.py
Release version with auditlog regex change.
> Prepare v0.0.1.dev33 release

- CHANGELOG.rst
- src/gordon_gcp/__init__.py
> Prepare v0.0.1.dev34 release

- CHANGELOG.rst
- src/gordon_gcp/__init__.py
> Prepare v0.0.1.dev35 release

- CHANGELOG.rst
- src/gordon_gcp/__init__.py
> Prepare v0.0.1.dev36 release

- src/gordon_gcp/plugins/janitor/authority.py
- src/gordon_gcp/plugins/janitor/gpubsub_publisher.py
- src/gordon_gcp/plugins/janitor/reconciler.py
- src/gordon_gcp/plugins/service/enricher.py
- src/gordon_gcp/plugins/service/event_consumer.py
- src/gordon_gcp/plugins/service/gdns_publisher.py
- tests/unit/clients/test_auth.py
- tests/unit/plugins/janitor/test_init.py
- tests/unit/plugins/service/test_init.py
The GAuthClient can now work with default credentials, so it is not required to have the keyfile provided anymore.
> make keyfile optional

- docs/config-janitor.rst
- docs/config-service.rst
- src/gordon_gcp/clients/http.py
- src/gordon_gcp/plugins/janitor/gpubsub_publisher.py
- src/gordon_gcp/plugins/janitor/reconciler.py
Update docs to reflect previous changes (the keyfile being optional now)
> Update docs that keyfile is optional

- .travis.yml
- requirements.txt
- test-requirements.txt
- tests/unit/clients/test_auth.py
- tests/unit/clients/test_gce.py
- tests/unit/clients/test_gcrm.py
- tests/unit/clients/test_gdns.py
- tests/unit/clients/test_http.py
- tests/unit/plugins/janitor/test_authority.py
- tests/unit/plugins/janitor/test_reconciler.py
Fixed version of https://github.com/spotify/gordon-gcp/pull/126
> Update aiohttp to 3.7.4

- MANIFEST.in
- catalog-info.yaml
> Add catalog-info
